---
pagetitle: "Publications | Kempenaers Lab"
number-sections: false
toc-title: "Content"
toc-depth: 2
warning: false
echo: false
lightbox: auto
fig-cap-location: bottom
---


```{r}
#| output: false
sapply(
c('data.table', 'glue', 'bib2df', 'bibtex', 'wordcloud', 'tm', 'stringr', 'pluralize'),
require, character.only = TRUE, quietly = TRUE)

source("./R/utils.R")

tools::bibstyle("thisBib", this.bibstyle() )


b = bibtex::read.bib('./CONTENT/biblio/publications.bib')

x = bib2df('./CONTENT/biblio/publications.bib') |> setDT()

x[, bb := format(b, style = "html", .bibstyle = "thisBib") ]

# when pdf is present
x[!is.na(PDF), PDF := paste0('./../../CONTENT/biblio/pdfs/', PDF)]
x[!is.na(PDF), bb := str_replace(bb, "</p>$", 
  glue_data(.SD, '<a href="{PDF}" target="_blank"> <i class="fas fa-file-pdf fa-lg text-success" ></i></a></p>', .sep = ""))]

setorder(x, -YEAR, -DATE, JOURNAL)

# pub groups
papers     = x[is.na(GROUP), ]
editorials = x[GROUP == 'editorial', ]


```

```{r, dev.args=list(bg="#363b42" ) }
#| fig-cap: 'The image is a visual representation of the most frequently used words in the titles of all publications.'

set.seed(3)

df = char_to_wordcloud(x$TITLE)

wordcloud::wordcloud(
  words        = df$word, 
  freq         = df$freq, 
  max.words    = 150, 
  random.order = FALSE, 
  rot.per      = 0.2, 
  colors       = colors1
  )

```
# __Editorials  {{< ai open-access >}}__


```{r}
#| echo: false
#| output: asis

editorials[, bb] |> cat()

cat('\n')


```


# __Publications {{< bi book >}} __



```{r}
#| echo: false
#| output: asis

for(y in unique(papers$YEAR) ) {

cat(paste("##", y, '\n\n'))

papers[YEAR == y, bb] |> cat()

cat('\n\n')


}

```
